### ISSUE TITLE
The Vitaccess survey is not loading the CSS properly on the first go inside app.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#1]
It is an online survey. On clicking Next, the CSS are loading properly and working fine.

**Comment by pavankumarkolla** [comment]
1.css Issue in Vitaccess is fixed. 
2. In Ipad there is an issue, The Next and Previous Button's text and image was not visible.

**Comment by pavankumarkolla** [comment]
The path was changed to fix the issue. So, Replace with below css link with old one in html file.

<link rel="stylesheet" href="themes/EQ5D/themes/eq5d_new.css" />

**Comment by Lintu00** [comment]
How do we apply this fix to other surveys that have different CSS files?

**Comment by pavankumarkolla** [comment]
Hi Lintu,
            when you are in the second question while taking the survey, debug that question and find the css file there. Copy the content and create new css file and place in the particular Project themes and also change the css link as below in html file.

<link rel="stylesheet" href="themes/Project_name/themes/css_filename.css" />

**Comment by pavankumarkolla** [comment]
Please follow the following procedure to copy the css content.
Step1: Once you run the project from studio start taking survey and go to the second or third question.
step2: press f12/right click and select inspect in chrome.
step3: 
![image](https://user-images.githubusercontent.com/26477412/31664073-aa2b9b40-b361-11e7-9606-e3549be5f4f5.png)
You will be getting as above image.
step4: In top there will be "Sources" tab. Select that.
step5: left side you will get the list.In that list open the folder which is like theme/Projectname/themes. Here you will find the css file. click on that it will open as below image.
![image](https://user-images.githubusercontent.com/26477412/31664239-588c4c02-b362-11e7-87f5-69e21a8afcc2.png)
step6: Now copy the css content and create a new css file.
step7:Place the new created file inside the themes of particular project.(Inside themes there will be the project list.If you open that project you get the themes folder again. Here you need to place that file).
step8: Final thing is change the path in html file as mentioned below.
<link rel="stylesheet" href="themes/Project_name/themes/css_filename.css" />
run the project and upload opgs file and check.

Still you face the issue please let me know.

**Comment by Lintu00** [comment]
Thank you Pavan,
I'll try the fix you suggested, although, I don't have a themes folder on my other survey projects, the .css file is in the root folder. Does this mean i have to create a themes folder inside my project in the OnePoint Global Studio and put my CSS file there for it to be recognized?

**Comment by pavankumarkolla** [comment]
You can place it inside the project also if you place it inside the project then give that reference path as href="themes/Project_name/css_filename.css".

**Comment by Lintu00** [comment]
Hello Pavan,
I tried following the steps you mentioned but had some problems.
First of all, this is my project structure in OnePoint Studio:
![step1](https://user-images.githubusercontent.com/13362435/32049262-153296d8-ba55-11e7-9567-8b8c90791121.PNG)
I have no themes folder so i include the css file in my html as:
`<link rel="stylesheet" href="baseline.css" />`
When i run my project in a web browser, even if i get to the second or third page i have no themes folder in my project resources
![step2](https://user-images.githubusercontent.com/13362435/32049845-433c30dc-ba57-11e7-982b-877c228cf5dd.PNG)
I don't really understand why i have to copy the css from the browser since i already have it in my project and since you said there is no need to create a "themes" folder then making a copy of my current css file and adding it in the same place shouldn't do anything new.

Maybe it would be easier if i send you the project files

Also, i don't understand where this file is located:

> <link rel="stylesheet" href="themes/EQ5D/themes/eq5d_new.css" />

I added this link in my EQ-5D project and i don't have the file, but it still works, so it must be uploaded somewhere.
How can i edit this file if i need to make css changes?

**Comment by pavankumarkolla** [comment]
Hi Lintu,
           Can you share me the project. I will make the changes and then provide it.

**Comment by Lintu00** [comment]
[PRO-CTCAE.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1422159/PRO-CTCAE.zip)
[Lifestyle.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1422161/Lifestyle.zip)

@pavankumarkolla , there are 5 other surveys but they share the same CSS file with one of the two surveys that i've added.
Should i also share those surveys or will it work if i give them the link to the new css files from these surveys after you make the changes? I'm asking since i'm not sure where the new files will be linked from.

**Comment by pavankumarkolla** [comment]
Hi Lintu,
           I have done with small changes in html for the projects which you shared, do follow the same for remaining projects. Instead of giving <link rel="stylesheet" href="pro-ctcae.css" /> , pls add sub-folder and place in that folder as <link rel="stylesheet" href="pro-ctcae_css/pro-ctcae.css" />
This should work I think, If you follow as same.
[Lifestyle.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1426817/Lifestyle.zip)
[PRO-CTCAE.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1426818/PRO-CTCAE.zip)

**Comment by Lintu00** [comment]
Hello @pavankumarkolla,
I uploaded the files you sent me in the OPG web app and updated the Lifestyle and PRO-CTCAE surveys with the new files but i'm still having the same issue as before (the first page still doesn't show any CSS styles). 
The only fix that has worked so far is the EQ-5D one where i didn't have to make any changes to my files and just added this link in html:
`<link rel="stylesheet" href="themes/EQ5D/themes/eq5d_new.css" />`

**Comment by pavankumarkolla** [comment]
Hi Lintu,
           Try with below updated projects.Include css path as "vitaccess/cssfilename" for other projects also except EQ-5D.If any css files are not loading please share me the css files.
[Lifestyle.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1429866/Lifestyle.zip)
[PRO-CTCAE.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1429867/PRO-CTCAE.zip)

**Comment by Lintu00** [comment]
Hi @pavankumarkolla,
The fix only works for the rest of the projects if the css file name is the same as the ones from the files you added. I'm guessing the css files were added somewhere since if i create a new project that has no css and add a link to vitaccess/pro-ctcae.css it will have that css. But if i create a new project and give it a css file with a different name while keeping the format that you suggested i will have the same CSS loading problem on the first page of the survey.
Another issue would be that if i make changes to the css file in one of the projects that you gave me, the changes are not visible.

**Comment by pavankumarkolla** [comment]
Hi Lintu,
The files which are adding are referring to the server path. So, we have created vitaccess folder and inside that we are placing the files in the Server. So, If you want to change or add the files let us know and share us the files that are adding newly.

**Comment by pavankumarkolla** [comment]
Hi Lintu,

The above fix is a work-around or a temporary solution for you. Currently we are working towards improving the approach to fix the issue for you. We will get back to you with more details on the fix.

Thank you.

**Comment by Lintu00** [comment]
Hello @pavankumarkolla,

Thank you for clearing things up, it makes sense now why I couldn't apply the fix on my own.
Until there is a better solution for doing this, can we update the `pro-ctcae.css` file on the server with this file? 
[pro-ctcae.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1454121/pro-ctcae.zip)

**Comment by pavankumarkolla** [comment]
Hi Lintu,

pro-ctcae.css file is updated in server. Use the same path as "vitaccess/pro-ctcae.css" in html.

**Comment by Lintu00** [comment]
Thank you Pavan
